server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URL}
          default-label: ${CONFIG_GIT_BRANCH}
          username: ${CONFIG_SERVER_GIT_USERNAME}
          password: ${CONFIG_SERVER_GIT_PASSWORD}